version: '3.7'

networks:
  mynetwork:
    driver: bridge

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - mynetwork
  